export const SEARCH_FRIEND_REQUEST = "SEARCH_FRIEND_REQUEST"

export const SEARCH_FRIEND_REQUEST_SUCCESS = "SEARCH_FRIEND_REQUEST_SUCCESS"

export const SEARCH_FRIEND_REQUEST_FAILURE = "SEARCH_FRIEND_REQUEST_FAILURE"
