export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";

export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";

export const GET_LOGGEDIN_USER_REQUEST = "GET_LOGGEDIN_USER_REQUEST"

export const GET_LOGGEDIN_USER_SUCCESS = "GET_LOGGEDIN_USER_SUCCESS"

export const GET_LOGGEDIN_USER_FAILURE = "GET_LOGGEDIN_USER_FAILURE"

export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST"

export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"

export const SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const LOGOUT_REQUEST_SUCCESS = "LOGOUT_REQUEST_SUCCESS";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";

export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS";

export const SIGNUP_REQUEST_FAILURE = "SIGNUP_REQUEST_FAILURE";

export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";

export const SEND_OTP_REQUEST_SUCCESS = "SEND_OTP_REQUEST_SUCCESS";

export const SEND_OTP_REQUEST_FAILURE = "SEND_OTP_REQUEST_FAILURE";
