
export const GET_CONVERSATION_REQUEST = "GET_CONVERSATION_REQUEST"

export const GET_CONVERSATION_SUCCESS = "GET_CONVERSATION_SUCCESS"

export const GET_CONVERSATION_FAILURE = "GET_CONVERSATION_FAILURE"

export const GET_MESSAGES_IN_CONVERSATION_REQUEST = "GET_MESSAGES_IN_CONVERSATION_REQUEST"

export const GET_MESSAGES_IN_CONVERSATION_SUCCESS = "GET_MESSAGES_IN_CONVERSATION_SUCCESS"

export const GET_MESSAGES_IN_CONVERSATION_FAILURE = "GET_MESSAGES_IN_CONVERSATION_FAILURE"

export const GET_MESSAGES_WITH_FRIEND_REQUEST = "GET_MESSAGES_WITH_FRIEND_REQUEST"

export const GET_MESSAGES_WITH_FRIEND_SUCCESS = "GET_MESSAGES_WITH_FRIEND_SUCCESS"

export const GET_MESSAGES_WITH_FRIEND_FAILURE = "GET_MESSAGES_WITH_FRIEND_FAILURE"
